#!/bin/bash

WOOF=~/.woof/woof

if [[ -z "$@" ]]; then
    echo "add h
add v
add-to-group
maximize
min
unmin
swap
swap-pane
change-plane
kill
remove
restore
move-to
eh
ev
rh
rv
activate-next-window
activate-prev-window
"
else
    if [[ ${1} == "kill" ]]; then
        CurrNextActiveWindow=$(${WOOF} $@)
        ActiveWindow=$(echo ${CurrNextActiveWindow} | sed 's/,.*//')
        NextWindow=$(echo ${CurrNextActiveWindow} | sed 's/.*,//')
        if [ $? == 0 ]; then
            if [ ! -z ${ActiveWindow} ]; then
                wmctrl -ic ${ActiveWindow}
            fi

            if [ ! -z ${NextWindow} ]; then
                xdotool windowactivate ${NextWindow}
            fi
        fi
    else
        ${WOOF} $@
    fi
fi
