#!/bin/bash

WOOF=~/.woof/woof.py

if [[ -z "$@" ]]; then
    echo "add h
add v
add-to-group
maximize
min
unmin
swap
swap-pane
change-plane
kill
remove
restore
move-to
eh
ev
rh
rv
activate-next-window
activate-prev-window
"
else
    echo $@ >> ~/log
    if [[ ${1} == "kill" ]]; then
        NextActiveWindow=$(${WOOF} $@)
        if [ $? == 0 ]; then
            wmctrl -c :ACTIVE:
            if [ -z NextActiveWindow ]; then
                xdotool windowactivate ${NextActiveWindow}
            fi
        fi
    else
        ${WOOF} $@
    fi
fi