#!/bin/bash

WOOF=~/.woof/woof.py

if [[ -z "$@" ]]; then
    echo "add h
add v
maximize
min
unmin
swap
swap-pane
change-plane
kill
remove
restore
move-to
expand-horz
expand-vert
reduce-horz
reduce-vert
"
else
    echo $@ >> ~/log
    if [[ ${1} == "add h" ]]; then
        ${WOOF} list "add h "
    elif [[ ${1} == "add h"* ]]; then
        ARGS=$(echo ${1} | sed 's/add h //')
        ${WOOF} addrofi h $ARGS
    elif [[ ${1} == "add v" ]]; then
        ${WOOF} list "add v "
    elif [[ ${1} == "add v"* ]]; then
        ARGS=$(echo ${1} | sed 's/add v //')
        ${WOOF} addrofi v $ARGS
    elif [[ ${1} == "swap-pane" ]]; then
        ${WOOF} $@
    elif [[ ${1} == "swap" ]]; then
        WINID=$(xdotool getactivewindow)
        ${WOOF} list "swap " | grep -v ${WINID}
    elif [[ ${1} == "swap"* ]]; then
        ARGS=$(echo ${1} | sed 's/swap //')
        ${WOOF} swaprofi $ARGS
    elif [[ ${1} == "kill" ]]; then
        ${WOOF} $@ && wmctrl -c :ACTIVE:
    elif [[ ${1} == "move-to" ]]; then
        ${WOOF} list "move-to " | grep -v $(xdotool getactivewindow)
    else
        ${WOOF} $@
    fi
fi