#!/bin/bash

ROOT_DIR=$(pwd)
BIN_DIR=~/bin/
WOOF_DIR=~/.woof/
BUILD_DIR=${ROOT_DIR}/_build/

./tools/build

mkdir -p ${BIN_DIR}
mkdir -p ${WOOF_DIR}
mkdir -p ${WOOF_DIR}/log

cp -v ${ROOT_DIR}/lib/helpers/woof ${BIN_DIR}
cp -v ${BUILD_DIR}/woof ${WOOF_DIR}